In [1]:
import pandas as pd
import plotly.express as px

In [2]:
df = pd.read_csv("Scouting_Database_Final.csv")
df.head()

,player,team,league,age,nation,pos,playing time_min,standard_sot%,standard_g/sh,team success_ppm,...,performance_crdy_per90,performance_crdr_per90,performance_fls_per90,performance_fld_per90,performance_off_per90,performance_crs_per90,performance_int_per90,performance_tklw_per90,standard_sh_per90,standard_sot_per90
0,Aaron Cresswell,West Ham,ENG-Premier League,34,ENG,DF,3495.0,3.70,0.000,1.296667,...,0.180258,0.0,0.386266,0.360515,0.077253,4.660944,1.004292,0.566524,0.360515,0.025751
1,Aaron Hickey,Brentford,ENG-Premier League,24-092,SCO,"DF,MF",3383.0,12.30,0.000,1.430000,...,0.345847,0.0,1.037541,1.622820,0.026604,1.010937,0.798108,1.143955,0.638487,0.106414
2,Aaron Ramsey,Nice,FRA-Ligue 1,31,WAL,MF,2111.0,30.30,0.025,0.975000,...,0.170535,0.0,1.279015,0.937944,0.170535,2.600663,0.810043,1.833254,1.193747,0.341071
3,Aaron Wan-Bissaka,Aston Villa,ENG-Premier League,28-288,COD,"DF,MF",8469.0,16.92,0.026,1.232000,...,0.116897,0.0,0.818278,0.541977,0.063762,1.540914,1.710946,1.296493,0.308183,0.085016
4,Aaron Zehnter,Wolfsburg,Unknown,20,GER,"DF,MF",1457.0,22.75,0.090,2.050000,...,0.000000,0.0,0.123542,0.000000,0.000000,2.223747,1.050103,0.617708,0.679478,0.308854

So this first plot will show the relationship between shots/90 and goals/90 with interactive hover

In [3]:
fig = px.scatter(
    df,
    x="standard_sh_per90",
    y="performance_gls_per90",
    hover_name="player",
    hover_data=["team", "league", "pos", "age"],
    color = "pos",
    title = "Goals per 90 vs. Shots per 90",
    labels = {
        "standard_sh_per90": "Shots per 90",
        "performance_gls_per90": "Goals per 90"
    }
)

fig.show()

So as you can see from that scatter plot, there is a positive correlation between shots and goals scored

The second visualization I'm going to do is a correlation map

In [6]:
#first i select the numeric columns
numeric_cols = [col for col in df.columns if col.endswith("_per90") or col.endswith("%")]
corr = df[numeric_cols].corr()

fig2 = px.imshow(
    corr,
    title = "Feature Correlation matrix",
    color_continuous_scale="RdBu",
    labels=dict(x="Features", y="Features", color="Correlation")
)

fig2.show()

In [5]:
corr

,standard_sot%,performance_gls_per90,performance_ast_per90,performance_g-pk_per90,performance_pk_per90,performance_crdy_per90,performance_crdr_per90,performance_fls_per90,performance_fld_per90,performance_off_per90,performance_crs_per90,performance_int_per90,performance_tklw_per90,standard_sh_per90,standard_sot_per90
standard_sot%,1.000000,0.458697,0.219340,0.457752,0.214066,-0.117216,-0.040152,0.009986,0.141484,0.320453,0.045484,-0.308178,-0.235779,0.379793,0.516457
performance_gls_per90,0.458697,1.000000,0.407773,0.980153,0.542079,-0.186800,-0.074745,0.086407,0.280080,0.629955,0.014147,-0.590765,-0.485226,0.828862,0.893793
performance_ast_per90,0.219340,0.407773,1.000000,0.403505,0.204831,-0.158849,-0.089864,-0.042167,0.265693,0.261808,0.474440,-0.378885,-0.159111,0.495297,0.474738
performance_g-pk_per90,0.457752,0.980153,0.403505,1.000000,0.364733,-0.189972,-0.074939,0.090732,0.276179,0.621377,-0.001453,-0.584266,-0.472374,0.818348,0.881901
performance_pk_per90,0.214066,0.542079,0.204831,0.364733,1.000000,-0.072102,-0.033408,0.021234,0.144796,0.324851,0.072607,-0.298087,-0.276688,0.424148,0.459723
performance_crdy_per90,-0.117216,-0.186800,-0.158849,-0.189972,-0.072102,1.000000,0.254608,0.513623,0.108392,-0.104987,-0.119449,0.202621,0.277494,-0.152085,-0.182704
performance_crdr_per90,-0.040152,-0.074745,-0.089864,-0.074939,-0.033408,0.254608,1.000000,0.134562,0.008081,-0.058445,-0.056268,0.122535,0.086987,-0.079586,-0.080807
performance_fls_per90,0.009986,0.086407,-0.042167,0.090732,0.021234,0.513623,0.134562,1.000000,0.320100,0.195904,-0.141246,-0.066971,0.203621,0.169486,0.128549
performance_fld_per90,0.141484,0.280080,0.265693,0.276179,0.144796,0.108392,0.008081,0.320100,1.000000,0.254213,0.185035,-0.309657,-0.027286,0.426534,0.370675
performance_off_per90,0.320453,0.629955,0.261808,0.621377,0.324851,-0.104987,-0.058445,0.195904,0.254213,1.000000,0.007066,-0.586817,-0.470759,0.652085,0.678155
performance_crs_per90,0.045484,0.014147,0.474440,-0.001453,0.072607,-0.119449,-0.056268,-0.141246,0.185035,0.007066,1.000000,-0.169668,0.061274,0.173512,0.119245
performance_int_per90,-0.308178,-0.590765,-0.378885,-0.584266,-0.298087,0.202621,0.122535,-0.066971,-0.309657,-0.586817,-0.169668,1.000000,0.558915,-0.637546,-0.647748
performance_tklw_per90,-0.235779,-0.485226,-0.159111,-0.472374,-0.276688,0.277494,0.086987,0.203621,-0.027286,-0.470759,0.061274,0.558915,1.000000,-0.452756,-0.483916
standard_sh_per90,0.379793,0.828862,0.495297,0.818348,0.424148,-0.152085,-0.079586,0.169486,0.426534,0.652085,0.173512,-0.637546,-0.452756,1.000000,0.951577
standard_sot_per90,0.516457,0.893793,0.474738,0.881901,0.459723,-0.182704,-0.080807,0.128549,0.370675,0.678155,0.119245,-0.647748,-0.483916,0.951577,1.000000

Based on the correlation matrix above we can see that the dark blue boxes show strong positive correlation. And those are columns like standard_sh_per90, standard_sot_per90, performance_gls_per90, performance_g-pk_per90, and standard_sot%
That means players who take more shots have more shots on target and they also score more goals. That defines the forwards

Then there's the deep red zones that show the Attacker vs Defender dynamic because deep red zones are features that show strong negative correlation. So the features that are being compared there are like performance_int_per90, performance_tklw_per90 and gls_per90, sh_per90, sot_per90

There's also a noticeable positive correlation between fouls commited, fouls drawn and yellow cards, which means that physical, high-dueling roles like Central Defensive Midfielders and Target Men Defenders engage in frequent contact.

So basically this heatmap proves that performance features naturally separate into distinct functional groups (Attackers, Creators, Defenders). Because feature pairs like Shots/90 and Interceptions/90 point in opposite vector directions

**`MODEL SELECTION`**

So i have decided to go with a model that will use the Cosine similarity algorithm.
Why:
1. Our goal is not predicting a single categorical label or numerical value. Instead, I aim to rank player profiles based on how closely their playstyle mirrors a target player.
2. Cosine Similarity calculates the angle between two feature vectors. This measures the shape of a player's output (their specific proportion of passes, tackles, and shots) rather than simply rewarding raw volume.

`FEATURE SCALING`

I will use StandardScaler because Cosine Similarity measures the angle between two feature vectors, and if features are on drastically different numerical scales, the larger feature will overpower the smaller ones and skew the angle.
It will preserve relative variance and it handles outliers.


If we look at our dataset we have features like standard_sot%  (values range from 0 to 100) and goals per 90 (0.0 to 0.8)
Without scaling, the standard shots on target feature will dominate the goals per 90 feature.